[en]
languageName = "English"
title = "alejandr00"
copyright = ""

[en.params]
subtitle = ""
keywords = ""
owner = ""
readMore = "Read more"
menuMore = "Show more"
readOtherPosts = "Read other posts"
missingContentMessage = "Page not found..."
missingBackButtonLabel = "Back to home page"

[en.params.logo]
  logoText = "Alejandr00"
  logoHomeLink = "/"

[en.menu]
  [[en.menu.main]]
    identifier = "about"
    name = "about"
    url = "/about"
  [[en.menu.main]]
    identifier = "gh"
    name = "github"
    url = "https://github.com/alejandro-angulo"
